# Generated by Django 4.0.4 on 2022-05-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок новости')),
                ('content', models.TextField(verbose_name='Содержимое новости')),
                ('time', models.CharField(max_length=25, verbose_name='Дата и Время')),
            ],
        ),
    ]
