# Generated by Django 4.0.4 on 2022-05-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='news',
            name='categ',
            field=models.CharField(max_length=30, null=True, verbose_name='Категория'),
        ),
    ]
